server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.1.11:3306/automa?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 000923
