server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: "000923"
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  global-config:
    db-config:
      table-prefix: au_


effectiveDate: 3
