server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: "000923"


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: au_
