server:
  port: 9091
spring:
  web:
    resources:
      static-locations: classpath:static/
  datasource:
    url: jdbc:mysql://47.95.122.63:3306/automa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: "admin"
  redis:
    host: 47.95.122.63
    port: 6379
    jedis:
      pool:
        max-wait: -1
    password: "000123"
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB

rocketmq:
  name-server: 47.95.122.63:9876
  producer:
    group: automa_group

mybatis-plus:
  global-config:
    db-config:
      table-prefix: au_

huaweiyun:
  obs:
    ak: A0AZNIUCHX7CVELZIQZR
    sk: k7DYqFUJzuOT8MxKvUsBvuADImnBqnAoGAqvQXqO
    bucketName: automa
    endpoint:  https://obs.cn-south-1.myhuaweicloud.com

effectiveDate: 3
